<?php
// This file is part of Moodle - http://moodle.org/

defined('MOODLE_INTERNAL') || die();

/**
 * Seed notification template config for new installs.
 */
function xmldb_local_spotaward_install(): void {
    $defaults = [
        'submission_pm_subject' => 'New Submission for Approval – {{course}} ({{module}})',
        'submission_pm_body' => "Hi {{program_manager_name}},\n\nA new submission has been raised for your review.\n\nDetails:\n- Course: {{course}}\n- Module: {{module}}\n- Mentor: {{mentor_name}}\n- Total Students: {{total_students}}\n- Moodle Link: {{moodle_link}}\n\nDescription:\n{{description}}\n\nPlease review and take necessary action.\n\nThanks,\n{{nominator_name}}",
        'pm_to_ss_subject' => 'SS Team Action Required - {{course}} ({{module}})',
        'pm_to_ss_body' => "Hi {{recipient_name}},\n\nThe following request has been approved by the Program Manager and assigned to the SS Team.\n\nDetails:\n- Course: {{course}}\n- Module: {{module}}\n- Mentor: {{mentor_name}}\n- Total Students: {{total_students}}\n- Moodle Link: {{moodle_link}}\n- Approved By: {{program_manager_name}}\n\nDescription:\n{{description}}\n\nPlease proceed with SS Team processing.\n\nThanks,\nEmertxe information technology",
        'pm_to_mentor_subject' => 'Update on Your Submission – {{course}} ({{module}})',
        'pm_to_mentor_body' => "Hi {{mentor_name}},\n\nYour submission has been reviewed by the Program Manager.\n\nStatus: {{status}}\n\nComments (if any):\n{{pm_comments}}\n\nRegards,\nEmertxe information technology",
        'ss_to_admin_subject' => 'PR Document Shared - {{course}} ({{module}})',
        'ss_to_admin_body' => "Hi {{recipient_name}},\n\nThe SS Team has shared the PR document for this request.\n\nDetails:\n- Course: {{course}}\n- Module: {{module}}\n- Mentor: {{mentor_name}}\n- Total Students: {{total_students}}\n\nThe uploaded PR document and any selected certificate attachment are included.\n\nThanks,\nEmertxe information technology",
        'record_closed_subject' => 'Spot Award Record Closed - {{course}} ({{module}})',
        'record_closed_body' => "Hi {{recipient_name}},\n\nThe Spot Award record has been closed.\n\nDetails:\n- Course: {{course}}\n- Module: {{module}}\n- Mentor: {{mentor_name}}\n- Program Manager: {{program_manager_name}}\n- Total Students: {{total_students}}\n- Closure Date: {{closure_date}}\n- Closed By: {{closed_by}}\n\nRegards,\nEmertxe information technology",
        'student_certificate_subject' => 'Your Spot Award Certificate - {{course}}',
        'student_certificate_body' => "Hi {{student_firstname}},\n\nCongratulations on receiving the Spot Award for {{course}}.\n\nDetails:\n- Course: {{course}}\n- Module: {{module}}\n- Award Category: {{award_category}}\n\nYour certificate is attached to this email.\n\nRegards,\nEmertxe information technology",
        'submission_pm_subject' => 'Spot Award Nominations Submitted - {{module}} | {{professional}} | {{course}}',
        'submission_pm_body' => "Dear {{program_manager_name}},\n\nI would like to inform you that I have submitted the Spot Award nominations for the {{module}} module. Kindly review and approve the nominations at the earliest so the distribution process can be initiated.\n\nNomination Details:\nProfessional: {{professional}}\nBatch ID: {{course}}\nModule: {{module}}\nTotal Nominations: {{total_students}} students\n\nRegards,\n{{mentor_name}}\nMentor - {{module}}\nEmertxe Information Technologies",
        'pm_to_ss_subject' => 'Spot Award Nominations Approved - {{module}} | {{professional}} | {{course}}',
        'pm_to_ss_body' => "Dear SS team,\n\nThis is to inform you that the Spot Award nominations submitted for {{module}} have been approved. Please proceed with further steps.\n\nApproval Details:\nProfessional: {{professional}}\nBatch ID: {{course}}\nModule: {{module}}\nTotal Approved Nominations: {{total_students}} students\n\nRegards,\n{{program_manager_name}}\nProgram Manager\nEmertxe Information Technologies",
        'pm_to_mentor_subject' => 'Spot Award Nominations Approved - {{module}} | {{professional}} | {{course}}',
        'pm_to_mentor_body' => "Dear {{mentor_name}},\n\nThis is to inform you that the Spot Award nominations submitted for {{module}} have been approved. Please proceed with further steps.\n\nApproval Details:\nProfessional: {{professional}}\nBatch ID: {{course}}\nModule: {{module}}\nTotal Approved Nominations: {{total_students}} students\n\nRegards,\n{{program_manager_name}}\nProgram Manager\nEmertxe Information Technologies",
        'ss_to_admin_subject' => 'Spot Award Certificate Print Request - {{module}} | {{course}} | {{professional}}',
        'ss_to_admin_body' => "Dear {{recipient_name}},\n\nRequesting for a Spot Award Certificate Print request.\n\nProcessing Details:\nProfessional: {{professional}}\nBatch ID: {{course}}\nModule: {{module}}\nTotal Certificates: {{total_students}} students\nMode: {{certificate_mode}}\n\nRegards,\nSS team\nSS team - {{course}}\nEmertxe Information Technologies",
        'record_closed_subject' => 'Spot Award Distribution Completed - {{module}} | {{professional}} | {{course}}',
        'record_closed_body' => "Dear {{recipient_name}},\n\nThis is to confirm that the Spot Award certificates for {{module}} have been successfully distributed to all nominated students.\n\nDistribution Summary:\nProfessional: {{professional}}\nBatch ID: {{course}}\nModule: {{module}}\nTotal Awards Distributed: {{total_students}} students\nDate of Distribution: {{closure_date}}\n\nThe Spot Award distribution process for this module is now complete.\n\nRegards,\nSS team\nSS team - {{course}}\nEmertxe Information Technologies",
    ];

    $defaults = array_merge($defaults, [
        'submission_pm_body' => '<p>Dear {{program_manager_name}},</p><p>I would like to inform you that I have submitted the Spot Award nominations for the {{module}} module. Kindly review and approve the nominations at the earliest so the distribution process can be initiated.</p><p><strong>Nomination Details:</strong></p><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:640px;"><thead><tr><th align="left">Field</th><th align="left">Value</th></tr></thead><tbody><tr><td>Professional</td><td>{{professional}}</td></tr><tr><td>Batch ID</td><td>{{course}}</td></tr><tr><td>Module</td><td>{{module}}</td></tr><tr><td>Total Nominations</td><td>{{total_students}} students</td></tr></tbody></table><p>Regards,<br>{{mentor_name}}<br>Mentor - {{module}}<br>Emertxe Information Technologies</p>',
        'pm_to_ss_body' => '<p>Dear SS team,</p><p>This is to inform you that the Spot Award nominations submitted for {{module}} have been approved. Please proceed with further steps.</p><p><strong>Approval Details:</strong></p><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:640px;"><thead><tr><th align="left">Field</th><th align="left">Value</th></tr></thead><tbody><tr><td>Professional</td><td>{{professional}}</td></tr><tr><td>Batch ID</td><td>{{course}}</td></tr><tr><td>Module</td><td>{{module}}</td></tr><tr><td>Total Approved Nominations</td><td>{{total_students}} students</td></tr></tbody></table><p>Regards,<br>{{program_manager_name}}<br>Program Manager<br>Emertxe Information Technologies</p>',
        'pm_to_mentor_body' => '<p>Dear {{mentor_name}},</p><p>This is to inform you that the Spot Award nominations submitted for {{module}} have been approved. Please proceed with further steps.</p><p><strong>Approval Details:</strong></p><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:640px;"><thead><tr><th align="left">Field</th><th align="left">Value</th></tr></thead><tbody><tr><td>Professional</td><td>{{professional}}</td></tr><tr><td>Batch ID</td><td>{{course}}</td></tr><tr><td>Module</td><td>{{module}}</td></tr><tr><td>Total Approved Nominations</td><td>{{total_students}} students</td></tr></tbody></table><p>Regards,<br>{{program_manager_name}}<br>Program Manager<br>Emertxe Information Technologies</p>',
        'ss_to_admin_body' => '<p>Dear {{recipient_name}},</p><p>Requesting for a Spot Award Certificate Print request.</p><p><strong>Processing Details:</strong></p><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:640px;"><thead><tr><th align="left">Field</th><th align="left">Value</th></tr></thead><tbody><tr><td>Professional</td><td>{{professional}}</td></tr><tr><td>Batch ID</td><td>{{course}}</td></tr><tr><td>Module</td><td>{{module}}</td></tr><tr><td>Total Certificates</td><td>{{total_students}} students</td></tr><tr><td>Mode</td><td>{{certificate_mode}}</td></tr></tbody></table><p>Regards,<br>SS team<br>SS team - {{course}}<br>Emertxe Information Technologies</p>',
        'record_closed_body' => '<p>Dear {{recipient_name}},</p><p>This is to confirm that the Spot Award certificates for {{module}} have been successfully distributed to all nominated students.</p><p><strong>Distribution Summary:</strong></p><table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;max-width:640px;"><thead><tr><th align="left">Field</th><th align="left">Value</th></tr></thead><tbody><tr><td>Professional</td><td>{{professional}}</td></tr><tr><td>Batch ID</td><td>{{course}}</td></tr><tr><td>Module</td><td>{{module}}</td></tr><tr><td>Total Awards Distributed</td><td>{{total_students}} students</td></tr><tr><td>Date of Distribution</td><td>{{closure_date}}</td></tr></tbody></table><p>The Spot Award distribution process for this module is now complete.</p><p>Regards,<br>SS team<br>SS team - {{course}}<br>Emertxe Information Technologies</p>',
        'cliq_submission_pm_subject' => 'Spot Award Nominations Submitted - {{module}} | {{professional}} | {{course}}',
        'cliq_submission_pm_body' => "Dear {{program_manager_name}},\n\nI would like to inform you that I have submitted the Spot Award nominations for the {{module}} module. Kindly review and approve the nominations at the earliest so the distribution process can be initiated.\n\n*Nomination Details*\n```Field                  Value\nProfessional           {{professional}}\nBatch ID               {{course}}\nModule                 {{module}}\nTotal Nominations      {{total_students}} students```\n\nRegards,\n{{mentor_name}}\nMentor - {{module}}\nEmertxe Information Technologies",
        'cliq_pm_to_ss_subject' => 'Spot Award Nominations Approved - {{module}} | {{professional}} | {{course}}',
        'cliq_pm_to_ss_body' => "Dear SS team,\n\nThis is to inform you that the Spot Award nominations submitted for {{module}} have been approved. Please proceed with further steps.\n\n*Approval Details*\n```Field                        Value\nProfessional                 {{professional}}\nBatch ID                     {{course}}\nModule                       {{module}}\nTotal Approved Nominations   {{total_students}} students```\n\nRegards,\n{{program_manager_name}}\nProgram Manager\nEmertxe Information Technologies",
        'cliq_pm_to_mentor_subject' => 'Spot Award Nominations Approved - {{module}} | {{professional}} | {{course}}',
        'cliq_pm_to_mentor_body' => "Dear {{mentor_name}},\n\nThis is to inform you that the Spot Award nominations submitted for {{module}} have been approved. Please proceed with further steps.\n\n*Approval Details*\n```Field                        Value\nProfessional                 {{professional}}\nBatch ID                     {{course}}\nModule                       {{module}}\nTotal Approved Nominations   {{total_students}} students```\n\nRegards,\n{{program_manager_name}}\nProgram Manager\nEmertxe Information Technologies",
        'cliq_ss_to_admin_subject' => 'Spot Award Certificate Print Request - {{module}} | {{course}} | {{professional}}',
        'cliq_ss_to_admin_body' => "Dear {{recipient_name}},\n\nRequesting for a Spot Award Certificate Print request.\n\n*Processing Details*\n```Field                  Value\nProfessional           {{professional}}\nBatch ID               {{course}}\nModule                 {{module}}\nTotal Certificates     {{total_students}} students\nMode                   {{certificate_mode}}```\n\nRegards,\nSS team\nSS team - {{course}}\nEmertxe Information Technologies",
        'cliq_record_closed_subject' => 'Spot Award Distribution Completed - {{module}} | {{professional}} | {{course}}',
        'cliq_record_closed_body' => "Dear {{recipient_name}},\n\nThis is to confirm that the Spot Award certificates for {{module}} have been successfully distributed to all nominated students.\n\n*Distribution Summary*\n```Field                      Value\nProfessional               {{professional}}\nBatch ID                   {{course}}\nModule                     {{module}}\nTotal Awards Distributed   {{total_students}} students\nDate of Distribution       {{closure_date}}```\n\nThe Spot Award distribution process for this module is now complete.\n\nRegards,\nSS team\nSS team - {{course}}\nEmertxe Information Technologies",
        'cliq_student_certificate_subject' => 'Your Spot Award Certificate - {{course}}',
        'cliq_student_certificate_body' => "Hi {{student_firstname}},\n\nCongratulations on receiving the Spot Award for {{course}}.\n\n*Details*\n```Field            Value\nCourse           {{course}}\nModule           {{module}}\nAward Category   {{award_category}}```\n\nYour certificate is attached to this email.\n\nRegards,\nEmertxe information technology",
    ]);

    foreach ($defaults as $key => $value) {
        set_config($key, $value, 'local_spotaward');
    }

    set_config(
        'nomination_course_shortnames',
        implode("\n", \local_spotaward\local\constants::default_nomination_course_shortname_prefixes()),
        'local_spotaward'
    );
}
